// Tooltip text descriptions for info buttons on the sidebar.
// keys = element ID in html
// values = descriptions
let tooltips_text = {
  "downloadDataInfo": "Download a spreadsheet of information on the current active nodes",
  "searchWordInfo": "Type an English word to find the corresponding sign on the graph",
  // "resetGraphInfo": "Return to full graph, remove all filters and brushing",
  "filtersInfo": "Limit the number of nodes displayed on the graph based on linguistic features",
  "seeTutorialInfo": "Go to network graph tutorial on asl-lex.org"
};

//These columns are the one which will show up in the sign data panel of the network graph, in the order below
// let ordered_property_list = ["EntryID", "LemmaID","Code","Batch","List","Item","YouTube Video","VimeoVideoHTML","VimeoVideo","SubtLexUSLog10WF","SignFrequency(M)","SignFrequency(SD)","SignFrequency(Z)","SignFrequency(N)","SignFrequency(M-Native)","SignFrequency(SD-Native)","SignFreq(Z-native)","SignFrequency(N-Native)","SignFrequency(M-Nonnative)","SignFrequency(SD-Nonnative)","SignFrequency(N-Nonnative)","SignFreq(Z-Nonnative)","DominantTranslation","PercentUnknown","PercentGlossAgreement","PercentUnknown(Native)","PercentGlossAgreement(Native)","PercentUnknown(Nonnative)","PercentGlossAgreement(Nonnative)","Iconicity(M)","Iconicity(SD)","Iconicity(Z)","Iconicity(N)","Iconicity_ID","IconicityType","D.Iconicity(M) all","D.Iconicity(SD) all","D.Iconicity(N) all","D.Iconicity(Z) all","D.Iconicity(M) native","D.Iconicity(SD) native","D.Iconicity(Z) native","D.Iconicity(N) native","Transparency(M)","Transparency SD","Transparency Z","LexicalClass","SignOnset(ms)","SignOffset(ms)","SignDuration(ms)","ClipDuration(ms)","InCDI","CDI Semantic Category","Initialized.2.0","FingerspelledLoanSign.2.0","Compound.2.0","NumberOfMorphemes.2.0","Handshape.2.0","MarkedHandshape.2.0","SelectedFingers.2.0","Flexion.2.0","FlexionChange.2.0","SpreadChange.2.0","ThumbPosition.2.0","ThumbContact.2.0","SignType.2.0","Movement.2.0","RepeatedMovement.2.0","MajorLocation.2.0","MinorLocation.2.0","SecondMinorLocation.2.0","Contact.2.0","NonDominantHandshape.2.0","UlnarRotation.2.0","HandshapeM2.2.0","MarkedHandshapeM2.2.0","SelectedFingersM2.2.0","FlexionM2.2.0","FlexionChangeM2.2.0","SpreadM2.2.0","SpreadChangeM2.2.0","ThumbPositionM2.2.0","ThumbContactM2.2.0","SignTypeM2.2.0","MovementM2.2.0","RepeatedMovementM2.2.0","MajorLocationM2.2.0","MinorLocationM2.2.0","SecondMinorLocationM2.2.0","ContactM2.2.0","NonDominantHandshapeM2.2.0","UlnarRotationM2.2.0","HandshapeM3.2.0","MarkedHandshapeM3.2.0","SelectedFingersM3.2.0","FlexionM3.2.0","FlexionChangeM3.2.0","SpreadM3.2.0","SpreadChangeM3.2.0","ThumbPositionM3.2.0","ThumbContactM3.2.0","SignTypeM3.2.0","MovementM3.2.0","RepeatedMovementM3.2.0","MajorLocationM3.2.0","MinorLocationM3.2.0","SecondMinorLocationM3.2.0","ContactM3.2.0","NonDominantHandshapeM3.2.0","UlnarRotationM3.2.0","HandshapeM4.2.0","MarkedHandshapeM4.2.0","SelectedFingersM4.2.0","FlexionM4.2.0","FlexionChangeM4.2.0","SpreadM4.2.0","SpreadChangeM4.2.0","ThumbPositionM4.2.0","ThumbContactM4.2.0","SignTypeM4.2.0","MovementM4.2.0","RepeatedMovementM4.2.0","MajorLocationM4.2.0","MinorLocationM4.2.0","SecondMinorLocationM4.2.0","ContactM4.2.0","NonDominantHandshapeM4.2.0","UlnarRotationM4.2.0","HandshapeM5.2.0","MarkedHandshapeM5.2.0","SelectedFingersM5.2.0","FlexionM5.2.0","FlexionChangeM5.2.0","SpreadM5.2.0","SpreadChangeM5.2.0","ThumbPositionM5.2.0","ThumbContactM5.2.0","SignTypeM5.2.0","MovementM5.2.0","RepeatedMovementM5.2.0","MajorLocationM5.2.0","MinorLocationM5.2.0","SecondMinorLocationM5.2.0","ContactM5.2.0","NonDominantHandshapeM5.2.0","UlnarRotationM5.2.0","HandshapeM6.2.0","MarkedHandshapeM6.2.0","SelectedFingersM6.2.0","FlexionM6.2.0","FlexionChangeM6.2.0","SpreadM6.2.0","SpreadChangeM6.2.0","ThumbPositionM6.2.0","ThumbContactM6.2.0","SignTypeM6.2.0","MovementM6.2.0","RepeatedMovementM6.2.0","MajorLocationM6.2.0","MinorLocationM6.2.0","SecondMinorLocationM6.2.0","ContactM6.2.0","NonDominantHandshapeM6.2.0","UlnarRotationM6.2.0","SignType.2.0Frequency","MajorLocation.2.0Frequency","MinorLocation.2.0Frequency","SecondMinorLocation.2.0Frequency","Movement.2.0Frequency","SelectedFingers.2.0Frequency","Flexion.2.0Frequency","FlexionChange.2.0Frequency","RepeatedMovement.2.0Frequency","Contact.2.0Frequency","SpreadChange.2.0Frequency","ThumbContact.2.0Frequency","ThumbPosition.2.0Frequency","UlnarRotation.2.0Frequency","PhonotacticProbability","Parameter.Neighborhood.Density.2.0","Neighborhood Density 2.0","SignBankAnnotationID","SignBankEnglishTranslations","SignBankLemmaID","SignBankSemanticField","SignBankReferenceID","bglm_aoa","empirical_aoa", "GuessAccuracy","H statistic","Spread.2.0Frequency", "Phonological Complexity"];
let ordered_property_list = ['EntryID', 'LemmaID', 'Code', 'Batch', 'EnglishWF(lg10)',
  'SignFrequency(M)', 'SignFrequency(SD)', 'SignFrequency(Z)',
  'SignFrequency(N)', 'Unknown','SignFrequency(M-Native)',
  'SignFrequency(SD-Native)', 'SignFreq(Z-native)',
  'SignFrequency(N-Native)', 'Unknown(Native)',
  'SignFrequency(M-Nonnative)', 'SignFrequency(SD-Nonnative)',
  'SignFrequency(N-Nonnative)', 'SignFreq(Z-Nonnative)',
  'Unknown(Nonnative)', 'DominantTranslation',
  'DominantTranslationAgreement',
  'DominantTranslationAgreement(Native)',
  'DominantTranslationAgreement(Nonnative)',
  'NondominantTranslations', 'Iconicity(M)', 'Iconicity(SD)',
  'Iconicity(Z)', 'Iconicity(N)', 'Iconicity_ID', 'LexicalClass',
  'Initialized.2.0', 'FingerspelledLoanSign.2.0', 'Compound.2.0',
  'NumberOfMorphemes.2.0', 'SignOnset(ms)', 'SignOffset(ms)',
  'SignDuration(ms)', 'ClipDuration(ms)', 'Handshape.2.0',
  'SelectedFingers.2.0', 'Flexion.2.0', 'FlexionChange.2.0',
  'Spread.2.0', 'SpreadChange.2.0', 'ThumbPosition.2.0',
  'ThumbContact.2.0', 'SignType.2.0', 'Movement.2.0',
  'RepeatedMovement.2.0', 'MajorLocation.2.0', 'MinorLocation.2.0',
  'SecondMinorLocation.2.0', 'Contact.2.0',
  'NonDominantHandshape.2.0', 'UlnarRotation.2.0',
  'SignType.2.0Frequency', 'MajorLocation.2.0Frequency',
  'MinorLocation.2.0Frequency', 'SecondMinorLocation.2.0Frequency',
  'Movement.2.0Frequency', 'SelectedFingers.2.0Frequency',
  'Flexion.2.0Frequency', 'FlexionChange.2.0Frequency',
  'RepeatedMovement.2.0Frequency', 'Contact.2.0Frequency',
  'Spread.2.0Frequency', 'SpreadChange.2.0Frequency',
  'ThumbContact.2.0Frequency', 'ThumbPosition.2.0Frequency',
  'UlnarRotation.2.0Frequency', 'Neighborhood Density 2.0',
  'Parameter.Neighborhood.Density.2.0', 'PhonotacticProbability',
  'Phonological Complexity', 'SignBankAnnotationID',
  'SignBankEnglishTranslations', 'SignBankLemmaID',
  'SignBankSemanticField', 'SignBankReferenceID', 'InCDI',
  'CDISemanticCategory', 'bglm_aoa', 'empirical_aoa'];

// these are the website display names for all the properties from the csv
let property_display_names = {'EntryID': 'Entry ID',
  'LemmaID': 'Lemma ID',
  'Code': 'Code (survey)',
  'Batch': 'Batch (survey)',
  'List': 'Code (survey)',
  'Item': 'Code (survey)',
  'EnglishWF(lg10)': 'English Word Frequency',
  'SignFrequency(M)': 'Frequency',
  'SignFrequency(SD)': 'Frequency SD',
  'SignFrequency(Z)': 'Frequency Z',
  'SignFrequency(N)': 'Frequency N',
  'Unknown': 'Sign Unknown',
  'SignFrequency(M-Native)': 'Frequency (Native)',
  'SignFrequency(SD-Native)': 'Frequency SD (Native) ',
  'SignFreq(Z-native)': 'Frequency Z (Native) ',
  'SignFrequency(N-Native)': 'Frequency N (Native) ',
  'Unknown(Native)': 'Sign Unknown (Native) (proportion)',
  'SignFrequency(M-Nonnative)': 'Frequency (Nonnative)',
  'SignFrequency(SD-Nonnative)': 'Frequency SD (Nonnative)',
  'SignFrequency(N-Nonnative)': 'Frequency Z (Nonnative)',
  'SignFreq(Z-Nonnative)': 'Frequency N (Nonnative)',
  'Unknown(Nonnative)': 'Sign Unknown (Nonnative) (proportion)',
  'DominantTranslation': 'Dominant Translation',
  'DominantTranslationAgreement': 'Dominant Translation Agreement (proportion)',
  'DominantTranslationAgreement(Native)': 'Dominant Translation Agreement (Native) (proportion)',
  'DominantTranslationAgreement(Nonnative)': 'Dominant Translation Agreement (Nonnative) (proportion)',
  'NondominantTranslations': 'Nondominant Translations',
  'Iconicity(M)': 'Non-Signer Iconicity',
  'Iconicity(SD)': 'Non-Signer Iconicity SD',
  'Iconicity(Z)': 'Non-Signer Iconicity Z',
  'Iconicity(N)': 'Non-Signer Iconicity N',
  'Iconicity_ID': 'Non-Signer Iconicity ID',
  'D.Iconicity(M)': 'Deaf Signer Iconicity',
  'D.Iconicity(SD)': 'Deaf Signer Iconicity SD',
  'D.Iconicity(N)': 'Deaf Signer Iconicity Z',
  'D.Iconicity(Z)': 'Deaf Signer Iconicity N',
  'D.Iconicity(M-native)': 'Deaf Signer Iconicity (Native)',
  'D.Iconicity(SD-native)': 'Deaf Signer Iconicity SD (Native)',
  'D.Iconicity(Z-native)': 'Deaf Signer Iconicity Z (Native)',
  'D.Iconicity(N-native)': 'Deaf Signer Iconicity N (Native)',
  'GuessConsistency': 'Consistency of Guesses',
  'GuessAccuracy': 'Accuracy of Guesses (proportion)',
  'Transparency(M)': 'Transparency',
  'Transparency SD': 'Transparency SD',
  'Transparency Z': 'Transparency Z',
  'LexicalClass': 'Lexical Class',
  'Initialized.2.0': 'Initialized Sign',
  'FingerspelledLoanSign.2.0': 'Fingerspelled Loan Sign',
  'Compound.2.0': 'Compound',
  'NumberOfMorphemes.2.0': 'Number Of Morphemes',
  'SignOnset(ms)': 'Sign Onset',
  'SignOffset(ms)': 'Sign Offset',
  'SignDuration(ms)': 'Sign Duration',
  'ClipDuration(ms)': 'Video Duration',
  'Handshape.2.0': 'Handshape',
  'SelectedFingers.2.0': 'Selected Fingers',
  'Flexion.2.0': 'Flexion',
  'FlexionChange.2.0': 'Flexion Change',
  'Spread.2.0': 'Spread',
  'SpreadChange.2.0': 'Spread Change',
  'ThumbPosition.2.0': 'Thumb Position',
  'ThumbContact.2.0': 'Thumb Contact',
  'SignType.2.0': 'Sign Type',
  'Movement.2.0': 'Path Movement',
  'RepeatedMovement.2.0': 'Repeated Movement',
  'MajorLocation.2.0': 'Major Location',
  'MinorLocation.2.0': 'Minor Location',
  'SecondMinorLocation.2.0': 'Second Minor Location',
  'Contact.2.0': 'Contact',
  'NonDominantHandshape.2.0': 'Nondominant Handshape',
  'UlnarRotation.2.0': 'Wrist Twist',
  'HandshapeM2.2.0': 'Handshape Morpheme 2',
  'SelectedFingersM2.2.0': 'Selected Fingers Morpheme 2',
  'FlexionM2.2.0': 'Flexion Morpheme 2',
  'FlexionChangeM2.2.0': 'Flexion Change Morpheme 2',
  'SpreadM2.2.0': 'Spread Morpheme 2',
  'SpreadChangeM2.2.0': 'Spread Change Morpheme 2',
  'ThumbPositionM2.2.0': 'Thumb Position Morpheme 2',
  'ThumbContactM2.2.0': 'Thumb Contact Morpheme 2',
  'SignTypeM2.2.0': 'Sign Type Morpheme 2',
  'MovementM2.2.0': 'Movement Morpheme 2',
  'RepeatedMovementM2.2.0': 'Repeated Movement Morpheme 2',
  'MajorLocationM2.2.0': 'Major Location Morpheme 2',
  'MinorLocationM2.2.0': 'Minor Location Morpheme 2',
  'SecondMinorLocationM2.2.0': 'Second Minor Location Morpheme 2',
  'ContactM2.2.0': 'Contact Morpheme 2',
  'NonDominantHandshapeM2.2.0': 'Nondominant Handshape Morpheme 2',
  'UlnarRotationM2.2.0': 'Wrist Twist Morpheme 2',
  'HandshapeM3.2.0': 'Handshape Morpheme 3',
  'SelectedFingersM3.2.0': 'Selected Fingers Morpheme 3',
  'FlexionM3.2.0': 'Flexion Morpheme 3',
  'FlexionChangeM3.2.0': 'Flexion Change Morpheme 3',
  'SpreadM3.2.0': 'Spread Morpheme 3',
  'SpreadChangeM3.2.0': 'Spread Change Morpheme 3',
  'ThumbPositionM3.2.0': 'Thumb Position Morpheme 3',
  'ThumbContactM3.2.0': 'Thumb Contact Morpheme 3',
  'SignTypeM3.2.0': 'Signtype Morpheme 3',
  'MovementM3.2.0': 'Movement Morpheme 3',
  'RepeatedMovementM3.2.0': 'Repeated Movement Morpheme 3',
  'MajorLocationM3.2.0': 'Major Location Morpheme 3',
  'MinorLocationM3.2.0': 'Minor Location Morpheme 3',
  'SecondMinorLocationM3.2.0': 'Second Minor Location Morpheme 3',
  'ContactM3.2.0': 'Contact Morpheme 3',
  'NonDominantHandshapeM3.2.0': 'Nondominant Handshape Morpheme 3',
  'UlnarRotationM3.2.0': 'Wrist Twist Morpheme 3',
  'HandshapeM4.2.0': 'Handshape Morpheme 4',
  'SelectedFingersM4.2.0': 'Selected Fingers Morpheme 4',
  'FlexionM4.2.0': 'Flexion Morpheme 4',
  'FlexionChangeM4.2.0': 'Flexion Change Morpheme 4',
  'SpreadM4.2.0': 'Spread Morpheme 4',
  'SpreadChangeM4.2.0': 'Spread Change Morpheme 4',
  'ThumbPositionM4.2.0': 'Thumb Position Morpheme 4',
  'ThumbContactM4.2.0': 'Thumb Contact Morpheme 4',
  'SignTypeM4.2.0': 'Sign Type Morpheme 4',
  'MovementM4.2.0': 'Movement Morpheme 4',
  'RepeatedMovementM4.2.0': 'Repeated Movement Morpheme 4',
  'MajorLocationM4.2.0': 'Major Location Morpheme 4',
  'MinorLocationM4.2.0': 'Minor Location Morpheme 4',
  'SecondMinorLocationM4.2.0': 'Second Minor Location Morpheme 4',
  'ContactM4.2.0': 'Contact Morpheme 4',
  'NonDominantHandshapeM4.2.0': 'Nondominant Handshape Morpheme 4',
  'UlnarRotationM4.2.0': 'Wrist Twist Morpheme 4',
  'HandshapeM5.2.0': 'Handshape Morpheme 5',
  'SelectedFingersM5.2.0': 'Selected Fingers Morpheme 5',
  'FlexionM5.2.0': 'Flexion Morpheme 5',
  'FlexionChangeM5.2.0': 'Flexion Change Morpheme 5',
  'SpreadM5.2.0': 'Spread Morpheme 5',
  'SpreadChangeM5.2.0': 'Spread Change Morpheme 5',
  'ThumbPositionM5.2.0': 'Thumb Position Morpheme 5',
  'ThumbContactM5.2.0': 'Thumb Contact Morpheme 5',
  'SignTypeM5.2.0': 'Sign Type Morpheme 5',
  'MovementM5.2.0': 'Movement Morpheme 5',
  'RepeatedMovementM5.2.0': 'Repeated Movement Morpheme 5',
  'MajorLocationM5.2.0': 'Major Location Morpheme 5',
  'MinorLocationM5.2.0': 'Minor Location Morpheme 5',
  'SecondMinorLocationM5.2.0': 'Second Minor Location Morpheme 5',
  'ContactM5.2.0': 'Contact Morpheme 5',
  'NonDominantHandshapeM5.2.0': 'Nondominant Handshape Morpheme 5',
  'UlnarRotationM5.2.0': 'Wrist Twist Morpheme 5',
  'HandshapeM6.2.0': 'Handshape Morpheme 6',
  'SelectedFingersM6.2.0': 'Selected Fingers Morpheme 6',
  'FlexionM6.2.0': 'Flexion Morpheme 6',
  'FlexionChangeM6.2.0': 'Flexion Change Morpheme 6',
  'SpreadM6.2.0': 'Spread Morpheme 6',
  'SpreadChangeM6.2.0': 'Spread Change Morpheme 6',
  'ThumbPositionM6.2.0': 'Thumb Position Morpheme 6',
  'ThumbContactM6.2.0': 'Thumb Contact Morpheme 6',
  'SignTypeM6.2.0': 'Sign Type Morpheme 6',
  'MovementM6.2.0': 'Movement Morpheme 6',
  'RepeatedMovementM6.2.0': 'Repeated Movement Morpheme 6',
  'MajorLocationM6.2.0': 'Major Location Morpheme 6',
  'MinorLocationM6.2.0': 'Minor Location Morpheme 6',
  'SecondMinorLocationM6.2.0': 'Second Minor Location Morpheme 6',
  'ContactM6.2.0': 'Contact Morpheme 6',
  'NonDominantHandshapeM6.2.0': 'Nondominant Handshape Morpheme 6',
  'UlnarRotationM6.2.0': 'Wrist Twist Morpheme 6',
  'SignType.2.0Frequency': 'Sign Type Frequency',
  'MajorLocation.2.0Frequency': 'Major Location Frequency',
  'MinorLocation.2.0Frequency': 'Minor Location Frequency',
  'SecondMinorLocation.2.0Frequency': 'Second Minor Location Frequency',
  'Movement.2.0Frequency': 'Movement Frequency',
  'SelectedFingers.2.0Frequency': 'Selected Fingers Frequency',
  'Flexion.2.0Frequency': 'Flexion Frequency',
  'FlexionChange.2.0Frequency': 'Flexion Change Frequency',
  'RepeatedMovement.2.0Frequency': 'Repeated Movement Frequency',
  'Contact.2.0Frequency': 'Contact Frequency',
  'Spread.2.0Frequency': 'Spread Frequency',
  'SpreadChange.2.0Frequency': 'Spread Change Frequency',
  'ThumbContact.2.0Frequency': 'Thumb Contact Frequency',
  'ThumbPosition.2.0Frequency': 'Thumb Position Frequency',
  'UlnarRotation.2.0Frequency': 'Ulnar Rotation Frequency',
  'Neighborhood Density 2.0': 'Neighborhood Density',
  'Parameter.Neighborhood.Density.2.0': 'Parameter Neighborhood Density',
  'PhonotacticProbability': 'Phonotactic Probability',
  'Phonological Complexity': 'Phonological Complexity',
  'SignBankAnnotationID': 'SignBank Annotation ID',
  'SignBankEnglishTranslations': 'SignBank English Translations',
  'SignBankLemmaID': 'SignBank Lemma ID',
  'SignBankSemanticField': 'SignBank Semantic Field',
  'SignBankReferenceID': 'SignBank Reference ID',
  'InCDI': 'In CDI',
  'CDISemanticCategory': 'CDI Semantic Category',
  'bglm_aoa': 'Age Of Acquisition',
  'empirical_aoa': 'Age Of Acquisition (Empirical)'};
